server:
  port: 8083
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/UserProfile?useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Seoul
    username: root
    password: '!@#gmlfkr7236'
  jpa:
    show-sql:true